apiVersion: v1
kind: Service
metadata:
  name: project-frontend-service
  namespace: my-app
spec:
  type: NodePort
  selector:
    app: project-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007