name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      continue-on-error: true  # Fallback if checkout fails
    - name: Fallback to manual pull
      run: |
        Write-Output "Ensuring latest code..."
        if (Test-Path "./freelance-marketplace-app") {
          cd ./freelance-marketplace-app
          git pull origin main
        } else {
          git clone https://github.com/maleeknoob/freelance-marketplace-app.git
          cd freelance-marketplace-app
        }
      shell: powershell
    - name: Start Minikube
      run: |
        Write-Output "Starting Minikube..."
        try {
          minikube start --driver=docker --force
          Write-Output "Minikube started successfully"
        } catch {
          Write-Output "Minikube start failed: $_"
          exit 1
        }
        minikube status
      shell: powershell
    - name: Set up Docker to use Minikube's environment
      run: |
        Write-Output "Configuring Docker to use Minikube's daemon..."
        & minikube -p minikube docker-env | Invoke-Expression
        docker info --format '{{.ServerVersion}}'
      shell: powershell
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      shell: powershell
    - name: Build and Push Backend Image
      run: |
        cd backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/project-backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/project-backend:latest
      shell: powershell
    - name: Build and Push Frontend Image
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/project-frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/project-frontend:latest
      shell: powershell
    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
        kubectl get pods -n my-app -o wide
      shell: powershell